name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_PAT }}
          template: terminal
          user: studio-23-xyz
          filename: metrics.svg
          base: header, repositories
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_history_limit: 1
          plugin_people: yes
          plugin_people_types: contributors
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Dhaka
          plugin_traffic: yes
          plugin_followup: yes
          plugin_followup_indepth: yes

