name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_PAT }}
          template: markdown
          filename: ./profile/README.md
          markdown: >-
            https://raw.githubusercontent.com/Studio-23-xyz/.github/main/Template.md
          config_output: markdown
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_topics: yes
          plugin_isocalendar: yes
          plugin_languages: yes
